solve CounterButton
js-tasks-ru/vue-20230320_n-zbiranik pull request #13
Opened 2023-04-17 11:36 UTC by natkazb

2023-04-17 11:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-17 11:59 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-17 12:00 UTC, natkazb commented
в UiImageUploader во время загрузки при повторном клике в консоли браузера ошибка
```
ntime-core.esm-bundler.js:40 [Vue warn]: Unhandled error during execution of component event handler 
  at <UiImageUploader uploader=fn<uploadImage> onSelect=fn<bound handleSelect> onUpload=fn<bound handleUpload>  ... > 
  at <App>
warn2 @ runtime-core.esm-bundler.js:40
logError @ runtime-core.esm-bundler.js:230
handleError @ runtime-core.esm-bundler.js:222
callWithErrorHandling @ runtime-core.esm-bundler.js:176
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
emit @ runtime-core.esm-bundler.js:730
onChange @ UiImageUploader.vue:42
_mergeProps.onChange._cache.<computed>._cache.<computed> @ UiImageUploader.vue:9
callWithErrorHandling @ runtime-core.esm-bundler.js:173
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:182
invoker @ runtime-dom.esm-bundler.js:345
runtime-core.esm-bundler.js:40 [Vue warn]: Unhandled error during execution of native event handler 
  at <UiImageUploader uploader=fn<uploadImage> onSelect=fn<bound handleSelect> onUpload=fn<bound handleUpload>  ... > 
  at <App>
warn2 @ runtime-core.esm-bundler.js:40
logError @ runtime-core.esm-bundler.js:230
handleError @ runtime-core.esm-bundler.js:222
(anonymous) @ runtime-core.esm-bundler.js:185
Promise.catch (async)
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:184
invoker @ runtime-dom.esm-bundler.js:345
App.vue:60 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at Proxy.handleSelect (App.vue:60:39)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at emit (runtime-core.esm-bundler.js:730:9)
    at Proxy.onChange (UiImageUploader.vue:42:12)
    at _mergeProps.onChange._cache.<computed>._cache.<computed> (UiImageUploader.vue:9:23)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at HTMLInputElement.invoker (runtime-dom.esm-bundler.js:345:9)
h
```
но тесты все проходят

2023-04-17 12:26 UTC, ShGKme requested changes
Во время загрузки отображается текст не только о загрузке.

А вот ошибка, которую вы написали, у меня не проявляется, в консоли всё чисто...

![image](https://user-images.githubusercontent.com/25978914/232483337-ffee737e-ee1d-4892-bd64-90a5fb93a43b.png)

2023-04-17 12:26 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +      <span v-if="loading" class="image-uploader__text">Загрузка...</span>
Вместо дублирования одного узла три раза с одинаковыми атрибутами, лучше динамически вычислять только меняющуюся часть. Например, вынести текст узла в вычисляемое свойство.

Кроме того, эти узлы не в цепочке `v-else-if`, поэтому Vue будет считать, что тут может быть 1, а может быть и два узла, будет чуть-чуть менее оптимально

2023-04-18 16:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-18 16:19 UTC, natkazb commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +      <span v-if="loading" class="image-uploader__text">Загрузка...</span>
это я поправила

2023-04-18 16:24 UTC, natkazb commented
не проходит тест
● forms/MeetupForm › MeetupForm › MeetupForm должен порождать событие submit по сабмиту формы с новыми данными программы митапа

не могу понять, почему
дайте пожалуйста подсказку)

2023-04-18 17:53 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    <div class="meetup-form__content">
У `submit` нужно отменять действие по умолчанию с `prevent`. Иначе браузерная форма нативно перезагружает страницу, отправляя данные на "сервер".

2023-04-19 01:58 UTC, natkazb commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    <div class="meetup-form__content">
ага, я исправила на @submit.prevent="sendForm" , но ошибка всё та же (

2023-04-19 05:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-19 08:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-19 09:00 UTC, natkazb commented
и ещё вопрос по MeetupAgendaItemForm
про работу с startsAt и endsAt - на веб форме я не вижу проблем своего решения, но тесты говорят иначе
что я делаю не так?

2023-04-20 15:36 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
Вместо 6 отслеживаний за полями объекта здесь можно использовать одно отслеживание глубоко за всем объектом.

2023-04-20 15:36 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    },
В качестве файла должен быть именно весь целиком объект файла. Так его можно загрузить на сервер и в целом с ним дальше работать. А вот имя файла ничего не даёт, с ним ничего не сделать.

2023-04-21 13:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-21 13:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-21 13:30 UTC, natkazb commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    },
исправлено

2023-04-21 13:30 UTC, natkazb commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    },
изменено

2023-04-21 13:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-21 13:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-21 13:42 UTC, natkazb commented
один тест не проходит
● forms/MeetupForm › MeetupForm › MeetupForm должен порождать событие submit по сабмиту формы с новыми данными программы митапа
@ShGKme  можно еще подсказок, пожалуйста?

2023-04-21 18:28 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    },
Искать элемент по ID при обновлении не совсем корректно.

Нет гарантии что после обновления пункта программы у него не поменяется ID. Например, если компонент получает каким-то образом при сохранении более реальный ID.

Даже с гарантированно неизменяющимся ID это лишние действия.

Конкретный экземпляр компонента формы пункта программы отвечает за редактирование конкретного пункта программы. Например, вторая форма редактирует именно второй пункт программы, третья форма - третий и так далее. Она получает на вход объект их конкретного элемента массива и редактирует именно этот элемент.

Поэтому не нужно при любом изменении полным перебором (findIndex) искать, какой именно пункт поменялся.

2023-04-22 08:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-22 09:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-22 09:10 UTC, natkazb commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    },
и вправду тесты сейчас проходят, спасибо :)

2023-04-22 09:46 UTC, ShGKme reviewed
Все решённые задачи приняты

2023-04-23 06:50 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-04-23 06:52 UTC, natkazb commented
я добавила ещё задач сюда, теперь все тесты проходят в этой ветке, примите пожалуйста pr

2023-04-23 10:42 UTC, ShGKme approved these changes
Все задачи приняты

2023-04-23 10:43 UTC, merged